title: Sheng Dai
email:
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ds2010.github.io"

# Analytics
analytics:
  provider: "google-gtag" # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    measurement_id: "G-PDR51VNJYH"
    anonymize_ip: # true, false (default)

# Build settings
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle

timezone: European/Helsinki
